version: '3.0'
services:
    api:
        build:
            context: ./api
        environment:
            - PORT=8081
        ports:
            - "8081:8081"
        networks:
            - personal
    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: interviews
            DB_URL: mongodb://root:interviews@mongo:27017
        ports:
            - "27017:27017"
        networks:
            - personal
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8082:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: interviews
            ME_CONFIG_MONGODB_URL: mongodb://root:interviews@mongo:27017/

        networks:
            - personal
networks:
    personal:
